# config.yaml

debug: true

visualize: false

DEV:
  server: "jdbc:sqlserver://fortrack-maz-sdb-san-dev-01.database.windows.net"
  database: "FortrackDB"

QA:
  server: "jdbc:sqlserver://fortrack-maz-sdb-san-qa-01.database.windows.net"
  database: "FortrackDB"

random_forest:
  regression:
    n_estimators: [100, 200]
    max_depth: [null, 10]
    min_samples_split: [2, 5]
    min_samples_leaf: [1, 3]
    random_state: [42]
    oob_score: [true]